# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  persistCredentials: true
  
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: npm run install

- script: npm test
  displayName: npm run test
  condition: succeeded()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
  condition: succeeded()

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar'
    organization: 'marmer-github'
    scannerMode: 'CLI'
    configMode: 'file'
  condition: succeeded()

- task: SonarCloudAnalyze@1
  condition: succeeded()

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'  
  condition: succeeded()

- script: |
    git config user.email "Mariano.Mertinat@gmail.com"
    git config user.name "MarMer"
    npm run deploy -- -r https://$(github_pat)@github.com/marmer/time-log.git
  displayName: deploy
  continueOnError: false
  condition: succeeded()