# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: npm run install

- script: npm test
  displayName: npm run test

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar'
    organization: 'marmer-github'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- script: |
    git config user.email "Mariano.Mertinat@gmail.com"
    git config user.name "MarMer"
    npm run deploy
  displayName: deploy