name: Build and deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        if: success()

      - run: npm test
        env:
          CI: true
        if: success()
        
      - run: npm install -g sonarqube-scanner
        if: success() && matrix.node-version == '12.x'
        
      - run: sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success() && matrix.node-version == '12.x'

      - run: npm run build --if-present
        if: success() && github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
        
      - run: cp build/index.html build/404.html
        if: success() && github.ref == 'refs/heads/master' && matrix.node-version == '12.x'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          # CLEAN: true
        if: success() && github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
        
