name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TIME_LOG_GITHUB_TOKEN }}
        REACT_APP_OAUTH_CLIENT_ID: ${{ secrets.REACT_APP_OAUTH_CLIENT_ID }}
        REACT_APP_OAUTH_CLIENT_SECRET: ${{ secrets.REACT_APP_OAUTH_CLIENT_SECRET }}
        BRANCH: gh-pages
        FOLDER: build
