name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        if: success()

      - run: npm test
        env:
          CI: true
        if: success()
        
      - run: npm install -g sonarqube-scanner
        if: success()
        
      - run: sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()

      - run: npm run build --if-present
        env:
          REACT_APP_SOME_ENV_VAR: ${{ secrets.REACT_APP_SOME_ENV_VAR }}
          REACT_APP_OAUTH_CLIENT_ID: ${{ secrets.REACT_APP_OAUTH_CLIENT_ID }}
        if: ${{ success() && github.ref == "master"}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
        if: ${{ success() && github.ref == "master"}}
